"""playlist: add win_condition

Revision ID: bd9fa635a476
Revises: b312725e4acb
Create Date: 2026-07-03 05:51:36.633762

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bd9fa635a476"
down_revision: str | Sequence[str] | None = "b312725e4acb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room_playlists",
        sa.Column("win_condition", sa.Enum("SCORE", "ACCURACY", "COMBO", "PP", name="wincondition"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room_playlists", "win_condition")
    # ### end Alembic commands ###
