"""Add immutable song compilations and their isolated fun leaderboards."""

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "ab7316d4c902"
down_revision = "9c6382d59251"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "soms_marathons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("compiler_version", sa.Integer(), nullable=False),
        sa.Column("segments", sa.JSON(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["lazer_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_soms_marathons_mode_deleted_id", "soms_marathons", ["ruleset_id", "deleted", "id"], unique=False
    )
    op.create_index(op.f("ix_soms_marathons_owner_id"), "soms_marathons", ["owner_id"], unique=False)
    op.create_table(
        "soms_marathon_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("marathon_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("max_combo", sa.Integer(), nullable=False),
        sa.Column("mods", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["marathon_id"],
            ["soms_marathons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["lazer_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_index(
        "ix_soms_marathon_scores_board", "soms_marathon_scores", ["marathon_id", "total_score", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_soms_marathon_scores_board", table_name="soms_marathon_scores")
    op.drop_table("soms_marathon_scores")
    op.drop_index(op.f("ix_soms_marathons_owner_id"), table_name="soms_marathons")
    op.drop_index("ix_soms_marathons_mode_deleted_id", table_name="soms_marathons")
    op.drop_table("soms_marathons")
    # ### end Alembic commands ###
