"""feat(db): SOMS activity outbox and supporter inbox

Revision ID: 9c6382d59251
Revises: eeedb0b27cc7
Create Date: 2026-09-09 04:43:48.591213

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9c6382d59251"
down_revision: str | Sequence[str] | None = "eeedb0b27cc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "soms_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_key", sa.String(length=160), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("recipient_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("announcement", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("chat_message_id", sa.Integer(), nullable=True),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_index("ix_soms_activity_delivered_id", "soms_activity", ["delivered", "id"], unique=False)
    op.create_index(
        "ix_soms_activity_recipient_read_id", "soms_activity", ["recipient_id", "is_read", "id"], unique=False
    )


def downgrade() -> None:
    """Remove only the SOMS activity inbox/outbox."""
    op.drop_index("ix_soms_activity_recipient_read_id", table_name="soms_activity")
    op.drop_index("ix_soms_activity_delivered_id", table_name="soms_activity")
    op.drop_table("soms_activity")
