"""user: remove is_restricted

Revision ID: 425b91532cb4
Revises: ee13ad926584
Create Date: 2025-10-05 11:11:46.391414

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "425b91532cb4"
down_revision: str | Sequence[str] | None = "ee13ad926584"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lazer_users", "is_restricted")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable
    op.add_column(
        "lazer_users", sa.Column("is_restricted", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True)
    )
    # Step 2: Set a default value for all existing rows
    op.execute("UPDATE lazer_users SET is_restricted = 0 WHERE is_restricted IS NULL")
    # Step 3: Alter the column to be NOT NULL
    op.alter_column("lazer_users", "is_restricted", nullable=False)
    # ### end Alembic commands ###
