"""screenshot: add db model

Revision ID: 5e5f052d0fe2
Revises: c5472f592d13
Create Date: 2026-04-19 08:25:45.244068

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "5e5f052d0fe2"
down_revision: str | Sequence[str] | None = "c5472f592d13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screenshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256_hash", sa.VARCHAR(length=64), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("last_access", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_screenshots_sha256_hash"), "screenshots", ["sha256_hash"], unique=False)
    op.create_index(op.f("ix_screenshots_user_id"), "screenshots", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("screenshots")
    # ### end Alembic commands ###
