"""score: add client_version

Revision ID: 33b85fd3771b
Revises: 1f3d2b7a9c41
Create Date: 2026-06-11 16:01:41.526857

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "33b85fd3771b"
down_revision: str | Sequence[str] | None = "1f3d2b7a9c41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "score_tokens",
        sa.Column("client_version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default=""),
    )
    op.add_column(
        "scores",
        sa.Column("client_version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "client_version")
    op.drop_column("score_tokens", "client_version")
    # ### end Alembic commands ###
